import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./ui/Header";
import SubNav from "./ui/SubNav";
import Footer from "./ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Teknoport",
  description: "Generated by TEKNOPORT",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {/* <SubNav /> */}
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
